# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_auto_20160629_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingameid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bonus',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.Item'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.Type'),
        ),
    ]
